### ISSUE TITLE
Akun Github Sains Data'22

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD2201#1]
Nama - NRP
Link profile GitHub

contoh
Sevi Nurafni - 20920001
https://github.com/sevinurafni

**Comment by riinndescartes** [comment]
Catherine Vanya P. - 2C2220008
https://github.com/riinndescartes

**Comment by RyanHakim24** [comment]
Ryan Fadhilah Faizal Hakim - 2C2220007
https://github.com/RyanHakim24

**Comment by cahyarahma** [comment]
Cahya Rahmawati -2C2220011
https://github.com/cahyarahma

**Comment by SilviNurinsan** [comment]
Silvi Nurinsan - 2C2220006
https://github.com/SilviNurinsan

**Comment by MulyatiEKaSaputri** [comment]
Mulyati Eka Saputri - 2C2220009
https://github.com/MulyatiEKaSaputri

**Comment by betrandathariq** [comment]
Betrand Atnariq Delpiero F - 2C2220001
https://github.com/betrandathariq

**Comment by ashafamultazam** [comment]
Ashafa multazam - 2C2220012
https://github.com/ashafamultazam

**Comment by IndrNurSukmawati** [comment]
Indri Nur Sukmawati - 2C2220010
https://github.com/IndrNurSukmawati

**Comment by cahyarahma** [comment]
Cahya Rahmawati_2C2220011
[2C2220011_CahyaRahmawati_TugasPekan1.pdf](https://github.com/sevinurafni/SD2201/files/14492189/2C2220011_CahyaRahmawati_TugasPekan1.pdf)

**Comment by SagaraAndiLS** [comment]
Sagara Andi Ladzuardi Suwarsa - 2C2220004

https://github.com/SagaraAndiLS

**Comment by tenideinarosa** [comment]
Teni Deinarosa Hermalia -2C2220005 
https://github.com/TeniDeinarosa2C2220005
