### ISSUE TITLE
Tugas Pekan 2

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD2201#3]

**Comment by riinndescartes** [comment]
Catherine V. Pang - 2C2220008 
Tugas pekan 2 
MK Pengantar Model Linear
Uji Koefisien Regresi dan Uji Linearitas

https://github.com/riinndescartes/Pengantar-Model-Linear/blob/main/MK%20Pengantar%20Model%20Linear%20tugas%20(2)%20Uji%20Koefisien%20Regresi%20dan%20Uji%20Linearitas%20.pdf

**Comment by RyanHakim24** [comment]
Ryan Fadhilah Faizal Hakim - 2C2220007

Tugas Pekan 2:
https://github.com/RyanHakim24/2C2220007_Ryan_Tugas2_PML

**Comment by betrandathariq** [comment]
Betrand Athariq Delpiero F - 2C2220001
Tugas Pekan 2 :
[2C2220001_BetrandAthariqDelpieroF_Tugas Pekan2.pdf](https://github.com/sevinurafni/SD2201/files/14601743/2C2220001_BetrandAthariqDelpieroF_Tugas.Pekan2.pdf)

**Comment by MulyatiEKaSaputri** [comment]
Mulyati Eka Saputri - 2C2220009
Tugas Pekan 2
[2C2220009_MulyatiEkaSaputri_TugasPekan2.pdf](https://github.com/sevinurafni/SD2201/files/14603242/2C2220009_MulyatiEkaSaputri_TugasPekan2.pdf)

**Comment by IndrNurSukmawati** [comment]
Indri Nur Sukmawati - 2C2220010
Tugas Pekan 2
[2C2220010_IndriNurSukmawati_TugasPekan2.pdf](https://github.com/sevinurafni/SD2201/files/14610228/2C2220010_IndriNurSukmawati_TugasPekan2.pdf)

**Comment by SilviNurinsan** [comment]
Silvi Nurinsan-2C2220006
Tugas Pekan 2
[2C2220006_SilviNurinsan_tugas pekan 2.pdf](https://github.com/sevinurafni/SD2201/files/14617526/2C2220006_SilviNurinsan_tugas.pekan.2.pdf)

**Comment by tenideinarosa** [comment]
Teni Deinarosa Hermalia - 2C2220005
Tugas Pekan 2
[Tugas pekan2_TeniDeinarosa_2c2220005.pdf](https://github.com/sevinurafni/SD2201/files/14626276/Tugas.pekan2_TeniDeinarosa_2c2220005.pdf)

**Comment by cahyarahma** [comment]
Cahya rahmawati 2C2220011
Tugas pekan 2 
[Uploading Cahya Rahmawati2C2220011-Tugas Pekan 2.pdf…]()

**Comment by cahyarahma** [comment]
Cahya Rahmawati 2C2220011
Tugas pekan 2
[Cahya Rahmawati2C2220011-Tugas Pekan 2.pdf](https://github.com/sevinurafni/SD2201/files/14627840/Cahya.Rahmawati2C2220011-Tugas.Pekan.2.pdf)

**Comment by SagaraAndiLS** [comment]
Sagara Andi Ladzuardi Suwarsa - 2C2220004
Tugas pekan 2:
![2C2220004_Sagara Andi L S_Tugas Pekan 2.pdf](https://github.com/sevinurafni/SD2201/files/14661525/2C2220004_Sagara.Andi.L.S_Tugas.Pekan.2.pdf)

**Comment by ashafamultazam** [comment]
Ashafa multazam - 2C2220012
[tugas pekan 2 - Ashafa multazam - 2C2220012.pdf](https://github.com/sevinurafni/SD2201/files/14896009/tugas.pekan.2.-.Ashafa.multazam.-.2C2220012.pdf)
