### ISSUE TITLE
Tugas 3

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD2201#4]

**Comment by MulyatiEKaSaputri** [comment]
Mulyati Eka Saputri - 2C2220009
[Mulyati_Eka_Saputri_2C2220009_Tugas3.pdf](https://github.com/sevinurafni/SD2201/files/14861131/Mulyati_Eka_Saputri_2C2220009_Tugas3.pdf)

**Comment by SilviNurinsan** [comment]
Silvi Nurinsan - 2C2220006
[2C2220006_SilviNurinsan_TugasPekan3.pdf](https://github.com/sevinurafni/SD2201/files/14861167/2C2220006_SilviNurinsan_TugasPekan3.pdf)

**Comment by cahyarahma** [comment]
Cahya Rahmawati - 2C2220011
[CahyaRahmawati_2C2220011_Tugas3.pdf](https://github.com/sevinurafni/SD2201/files/14861175/CahyaRahmawati_2C2220011_Tugas3.pdf)

**Comment by SagaraAndiLS** [comment]
Sagara Andi Ladzuardi Suwarsa - 2C2220004

![2C2220004_Sagara Andi L S_Tugas 3.pdf](https://github.com/sevinurafni/SD2201/files/14861172/2C2220004_Sagara.Andi.L.S_Tugas.3.pdf)

**Comment by ashafamultazam** [comment]
Ashafa multazam - 2C2220012
[ashafa_multazam - Tugas_3.pdf](https://github.com/sevinurafni/SD2201/files/14861214/ashafa_multazam.-.Tugas_3.pdf)

**Comment by betrandathariq** [comment]
Betrand Athariq Delpiero F - 2C2220001
[BetrandAthariqDelpieroF_2C2220001_TugasPekan3.pdf](https://github.com/sevinurafni/SD2201/files/14889567/BetrandAthariqDelpieroF_2C2220001_TugasPekan3.pdf)

**Comment by riinndescartes** [comment]
Catherine V. P. - 2C2220008
https://github.com/riinndescartes/Pengantar-Model-Linear/blob/main/2C2220008CatherineVP-TugasPekan3.pdf

**Comment by tenideinarosa** [comment]
Teni Deinarosa Hermalia-2C2220005
[Tugas3_pengantarLinier_Teni deinarosa hermalia_2C2220005.PDF](https://github.com/sevinurafni/SD2201/files/14895771/Tugas3_pengantarLinier_Teni.deinarosa.hermalia_2C2220005.PDF)

**Comment by RyanHakim24** [comment]
Ryan F. F. Hakim - 2C2220007
https://github.com/RyanHakim24/2C2220007_Ryan_Tugas3_PML

**Comment by IndrNurSukmawati** [comment]
Indri Nur Sukmawati - 2C2220010

**Comment by IndrNurSukmawati** [comment]
Indri Nur Sukmawati - 2C2220010
[2C2220010_IndriNurSukmawati_TugasPekan3.pdf](https://github.com/sevinurafni/SD2201/files/14896102/2C2220010_IndriNurSukmawati_TugasPekan3.pdf)
