### ISSUE TITLE
Tugas 4

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD2201#5]
Tugas Kelompok
1. Hitung ulang secara manual contoh soal Y, X1, X2, X3 (Modul 4.2)
2. Bandingkan dengan hasil dari R

deadline: 23 April 2024, 23:59

**Comment by cahyarahma** [comment]
Kelompok 1
•Cahya Rahmawati 
•Sagara Andi L S
•Intan Wahyuni M

Cahya Rahmawati_2C2220011_Tugas 4|Kelompok 
https://drive.google.com/drive/folders/1exFXLVWGjQMTgKFWjSw21f_HNmzZZFC3

**Comment by SilviNurinsan** [comment]
Tugas 4
Kelompok 2
- Silvi Nurinsan (2C2220006)
- Muhammad Kamal Shidiq (2C2220003)
- Herodia Mahwil (2C2220015)

[Silvi Nurinsan_2C2220006_Tugas4_ Kelompok 2.pdf](https://github.com/sevinurafni/SD2201/files/15095904/Silvi.Nurinsan_2C2220006_Tugas4_.Kelompok.2.pdf)

**Comment by riinndescartes** [comment]
Tugas 4
Kelompok 4

1. Catherine V. Pang - 2C2220008
2. Mulyati Eka S. - 2C2220009
3. Ester S. - 2C2220016

[MAKALAH STUDI KASUS REGRESI LINEAR MULTIPLE UJI HIPOTESIS DAN INTERVAL KOEFISIEN REGRESI RESPON RATA-RATA DAN RESPON TUNGGAL Kelompok Catherine Eka Ester.pdf]

(https://github.com/sevinurafni/SD2201/files/15126897/MAKALAH.STUDI.KASUS.REGRESI.LINEAR.MULTIPLE.UJI.HIPOTESIS.DAN.INTERVAL.KOEFISIEN.REGRESI.RESPON.RATA-RATA.DAN.RESPON.TUNGGAL.Kelompok.Catherine.Eka.Ester.pdf)

**Comment by IndrNurSukmawati** [comment]
Tugas 4
Kelompok 5

    1. Teni Deinarosa Hermalia - 2C2220005
    2. Indri Nur Sukmawati - 2C2220010
    3. Assafa Multazam - 2C2220012

[Indri Nur Sukmawati_2C2220010_Tugas 4_Kelompok 5.pdf](https://github.com/sevinurafni/SD2201/files/15137720/Indri.Nur.Sukmawati_2C2220010_Tugas.4_Kelompok.5.pdf)

**Comment by RyanHakim24** [comment]
### Tugas 4
Kelompok 3:
* Ryan F F H - 2C2220007
* Betrand D - 2C2220001
* Lifa M - 2C2220014

**Link:**
https://github.com/RyanHakim24/TugasKelompok1_Kelompok3_PML
